//Povray v3 code generated by Open Babel (edited)
#declare BAS = true;
#declare TRANS = false;

#include "colors.inc"
#include "babel_povray3.inc"

#version 3.6;

//Atom coordinates for glycine (corrected from obabel output)
#declare mol_0_pos_1 = <-0.5, 0, 0>;    //C
#declare mol_0_pos_2 = <0.5, 0, 0>;     //C
#declare mol_0_pos_3 = <1.0, 0.5, 0>;   //O
#declare mol_0_pos_4 = <1.0, -0.5, 0>;  //O
#declare mol_0_pos_5 = <-1.0, 0, 0>;    //N

//Atoms
#declare mol_0_atom1 = object { Atom_C translate mol_0_pos_1 }
#declare mol_0_atom2 = object { Atom_C translate mol_0_pos_2 }
#declare mol_0_atom3 = object { Atom_O translate mol_0_pos_3 }
#declare mol_0_atom4 = object { Atom_O translate mol_0_pos_4 }
#declare mol_0_atom5 = object { Atom_N translate mol_0_pos_5 }

//Bonds
#declare mol_0_bond0 = cylinder { mol_0_pos_1, mol_0_pos_2, 0.1 pigment { color Yellow } }
#declare mol_0_bond1 = cylinder { mol_0_pos_2, mol_0_pos_3, 0.1 pigment { color Yellow } }
#declare mol_0_bond2 = cylinder { mol_0_pos_2, mol_0_pos_4, 0.1 pigment { color Yellow } }
#declare mol_0_bond3 = cylinder { mol_0_pos_1, mol_0_pos_5, 0.1 pigment { color Yellow } }

//Molecule definition
#declare mol_0 = union {
  object { mol_0_atom1 }
  object { mol_0_atom2 }
  object { mol_0_atom3 }
  object { mol_0_atom4 }
  object { mol_0_atom5 }
  object { mol_0_bond0 }
  object { mol_0_bond1 }
  object { mol_0_bond2 }
  object { mol_0_bond3 }
}
